version: 2.0
jobs:
  php8.1:
    machine:
      image: ubuntu-2004:current
    runs-on:
      docker:
        - image: php:8.1

        - image: docker:dind
          entrypoint: docker-init -- dockerd --host=tcp://0.0.0.0:2375
          privileged: True

    steps:
      - run: |
          apt update -y
          apt install -y git unzip

      - run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          php -r "unlink('composer-setup.php');"

      - checkout

      - restore_cache:
          keys:
            - 'dependencies-{{ checksum "composer.json" }}'

      - run: composer install --prefer-dist

      - save_cache:
          paths:
            - vendor
          key: 'dependencies-{{checksum "composer.json" }}'

      - run:
          name: Waiting for DinD (60s)
          command: sleep 60

      - run:
          name: Tests
          command: ./vendor/phpunit/phpunit/phpunit --verbose tests

workflows:
  version: 2
  test-docker-client:
    jobs:
      - php8.1
